{{- if .Values.loadbalancer.enabled }}
  {{- $port := .Values.loadbalancer.port }}
  {{- $loadbalancers := .Values.loadbalancers | int }}
  {{- $fullName := include "cp-kafka.fullname" . }}
  {{- $port := .Values.loadbalancer.port }}
  {{- $root := . }}
  {{- range $i, $e := until $loadbalancers }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-{{ $i }}-loadbalancer
  labels:
    app: {{ include "cp-kafka.name" $root }}
    chart: {{ template "cp-kafka.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
spec:
  type: LoadBalancer
  ports:
    - name: external
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
  selector:
    app: {{ include "cp-kafka.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}
